openapi: 3.0.0
info:
  title: cogit-ws.v1
  version: 1.0.0
  description: API passerelle pour le cogit
servers:
  - url: 'http://localhost:3000'
paths:
  /briques:
    get:
      summary: Get List Briques
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/brique.v1.yaml
              examples:
                repo-read-list:
                  value:
                    - name: amir
                    - name: samir
                    - name: cokpit
                    - name: fomration
                    - name: ota
                    - name: portik
                    - name: wrcent
                    - name: wrcepb
                    - name: stocdo
                repo-write-list:
                  value:
                    - name: cokpit
                    - name: fomration
                    - name: ota
                    - name: portik
      operationId: get-briques
      parameters:
        - schema:
            type: string
            enum:
              - REPO_READ
              - REPO_WRITE
              - REPO_ADMIN
          in: query
          name: permission
          allowEmptyValue: false
          description: |
            Filtre selon les droits d'accès au repos
          style: ''
      security:
        - Encoded username/password: []
      description: "Liste les briques déclarées dans Bitbucket (repositories)\nLa recherche peut être filtrée au niveau des permissions en paramètre de la requête.\n\n**Note on permissions:** \nIn absence of the permission query parameter the implicit 'read' permission is assumed. Please note that this permission is lower than the REPO_READ permission rather than being equal to it. The implicit 'read' permission for a given repository is assigned to any user that has any of the higher permissions, such as REPO_READ, as well as to anonymous users if the repository is marked as public. The important implication of the above is that an anonymous request to this resource with a permission level REPO_READ is guaranteed to receive an empty list of repositories as a result."
components:
  schemas: {}
  securitySchemes:
    Encoded username/password:
      type: http
      scheme: basic
      description: ''
